apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-blue-prd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: prd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/lkravi/eks_blueprints_workloads.git
    targetRevision: main
    path: teams/blue/prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true